---
- name: Prueba de Extraer RFC por category
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Extraer cambios de datos
      servicenow.itsm.change_request_info:
        query:
          - category: = DevOps
      register: result
